Temporarily disable new plyvel versions which don't build
The (fairly new, from 2 days ago) plyvel 1.0.0 broke it, so stick with
the working one until further investigated & fixed...

Error was:
plyvel/_plyvel.cpp: In function 'int __pyx_f_6plyvel_7_plyvel_parse_options(leveldb::Options*, bool, bool, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, int, PyObject*, PyObject*)':
plyvel/_plyvel.cpp:3341:22: error: 'struct leveldb::Options' has no member named 'max_file_size'
__pyx_v_options->max_file_size = __pyx_t_4;

plyvel 1.0.0 requires leveldb 1.20, and our Travis build installs
libleveldb1 1.15.0 (and there is no superior version in this
distribution), thus we are stuck with plyvel<1.0.0.

We should use plyvel>=0.9,<1.0.0 in case someone creates updates over
the 0.9 version.