Python API: protect from a bug in urllib3
Sometimes we see a stack trace ending with the following lines:

  File "/usr/lib/python3.7/site-packages/urllib3/util/wait.py", line 85, in select_wait_for_socket
    rready, wready, xready = _retry_on_intr(fn, timeout)
  ValueError: not enough values to unpack (expected 3, got 0)

We suspect this comes from a bad context switch from eventlet.