CLI: fix 'openio-admin rawx check' command
The command was not working and was returning
"AttributeError: 'Target' object has no attribute 'target'", due to an
incomplete refactoring of oio/crawler/integrity.py file.